--build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -36,19 +36,27 @@ jobs:
           #!/bin/bash
 
           WORKDIR=${{github.workspace}}
-
           BUILD_JSON="$WORKDIR/data/builds.json"
 
+          # Find the full path of the 'go' binary
+          GO_PATH=$(which go)
+
+          if [ -z "$GO_PATH" ]; then
+            echo "Error: 'go' is not installed or not in PATH."
+            exit 1
+          fi
+
           jq -c '.toBuild[]' $BUILD_JSON | while IFS= read -r item; do
-            CMD=$(echo "$item" | jq -r '.cmd')
-            PATH=$(echo "$item" | jq -r '.path' | sed "s|{{workdir}}|$WORKDIR|")
+            CMD=$(echo "$item" | jq -r '.cmd' | sed "s|{{go}}|$GO_PATH|g")
+            PATH=$(echo "$item" | jq -r '.path' | sed "s|{{workdir}}|$WORKDIR|g")
 
             echo "Executing: cd $PATH && $CMD"
 
             # Execute the build command
-            cd $PATH
+            cd "$PATH" || { echo "Error: Directory $PATH does not exist."; exit 1; }
             eval "$CMD"
           done
+
 
 
 
